// This file is generated by the server to provide Laravel data to the client
// The content is generated dynamically by the server and should not be modified manually
window.laravelData = window.laravelData || {};

// Always include the CSRF token
window.laravelData.csrfToken = '{{ $csrfToken }}';

// Include user data if available
@if(isset($user) && $user !== null)
window.laravelData.user = {!! json_encode($user, JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_TAG | JSON_HEX_AMP) !!};
@else
window.laravelData.user = null;
@endif
