name: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, gd, exif, fileinfo, bcmath, intl, sodium, sqlite3
        coverage: none

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        npm install -g npm@latest
        npm install

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mysql -h 127.0.0.1 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS laravel_testing;"
        cp .env.example .env
        php artisan key:generate
        php artisan config:clear

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel_testing
        DB_USERNAME: root
        DB_PASSWORD: password
      run: |
        php artisan migrate:fresh --seed
        php artisan test

  laravel-code-style:
    name: Check & fix styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, gd, exif, fileinfo, bcmath, intl, sodium, sqlite3
          coverage: none
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install Laravel Pint
        run: composer require laravel/pint --dev
      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test
